### ISSUE TITLE
API key leak

### ISSUE THREAD

**Issue by gkoberger** [alchemyplatform/docs-openapi-specs#133]
Hey there! I noticed you recently pushed a ReadMe API key, and just wanted to let you know it's public.

https://github.com/alchemyplatform/docs-openapi-specs/blob/6d06aef7aec21c6f14a2638f15483bcc88757e37/scripts/update.js

We've deleted it for you, but wanted to warn you :)

**Comment by bmoyroud** [comment]
yup - thanks @gkoberger !
