### ISSUE TITLE
Instructions on how to use

### ISSUE THREAD

**Issue by trile127** [alchemyplatform/docs-openapi-specs#27]
Is there an example on using the openapi-generator cli tool to generate an sdk client?
I tried it on body.yaml, no luck

**Comment by elanh** [comment]
Hey! these aren't quite compatible to be able to generate an SDK from, would need to modify the specs slightly but it's not something that we're supporting at the moment. Curious what type of SDK you're looking to generate?

**Comment by trile127** [comment]
I'm looking to do a python backend and flutter frontend type of thing. Maybe rust or C# .net 6.0 backend for fun.

**Comment by trile127** [comment]
Typically it would be easiest to have the openapi swagger docs open and someone can just go to https://petstore.swagger.io/

and point the openapi-generator cli tool to https://petstore.swagger.io/v2/swagger.json and generate an openapi client, and just make sure the api works with languages that use nullable

**Comment by elanh** [comment]
Ah got it - thanks for the context! Sadly, this won't quite work with the OpenAPI as is right now. We can work on modifying the files in the future to be able to do this though.

In terms of SDKs for python and flutter. The standard Web3 python SDK is Web3.py and I actually just stumbled upon a Flutter SDK a few weeks ago here: https://flutterawesome.com/an-alchemy-platform-client-for-flutter-dart/

Hope this helps!

**Comment by trile127** [comment]
Yeah, unfortunately it doesnt have everything, ill probably end up using it, needs some development.
